cmake_minimum_required(VERSION 3.22)
include("${PACKAGE_CONFIG}")
set(package_name "TE-2350-Antigravity-${VERSION}-windows-x64")
get_filename_component(output "${OUTPUT_DIR}" ABSOLUTE)
set(package "${output}/${package_name}")
set(archive "${output}/${package_name}.zip")
# Exact, confined paths only. Remove prior outputs before testing, including on failure.
if(NOT package_name MATCHES "^TE-2350-Antigravity-[0-9]+\\.[0-9]+\\.[0-9]+-windows-x64$")
    message(FATAL_ERROR "Unsafe package name")
endif()
file(REMOVE_RECURSE "${package}")
file(REMOVE "${archive}" "${archive}.sha256" "${output}/SHA256SUMS.txt")
include("${SOURCE_DIR}/cmake/Qualification.cmake")

foreach(binary IN ITEMS "${VST3_BINARY}" "${STANDALONE}" "${SCANNER}")
    if(NOT EXISTS "${binary}")
        message(FATAL_ERROR "Missing release binary: ${binary}")
    endif()
    file(SIZE "${binary}" size)
    if(size EQUAL 0)
        message(FATAL_ERROR "Empty release binary: ${binary}")
    endif()
endforeach()
set(stage "${BUILD_DIR}/release-staging/${package_name}")
file(REMOVE_RECURSE "${stage}")
file(MAKE_DIRECTORY "${stage}/VST3" "${stage}/Standalone")
file(COPY "${VST3_BUNDLE}" DESTINATION "${stage}/VST3")
file(COPY "${STANDALONE}" DESTINATION "${stage}/Standalone")
get_filename_component(bundle_name "${VST3_BUNDLE}" NAME)
get_filename_component(exe_name "${STANDALONE}" NAME)
set(staged_bundle "${stage}/VST3/${bundle_name}")
set(staged_binary "${staged_bundle}/Contents/x86_64-win/${bundle_name}")
set(staged_exe "${stage}/Standalone/${exe_name}")
if(NOT EXISTS "${staged_binary}" OR NOT EXISTS "${staged_bundle}/Contents/Resources/moduleinfo.json")
    message(FATAL_ERROR "Invalid Windows x64 VST3 bundle structure")
endif()
file(READ "${staged_bundle}/Contents/Resources/moduleinfo.json" moduleinfo)
foreach(cid IN ITEMS ABCDEF019182FAEB5465416754323335 ABCDEF011234ABCD5465416754323335)
    if(NOT moduleinfo MATCHES "${cid}")
        message(FATAL_ERROR "M12 VST3 identity changed: ${cid}")
    endif()
endforeach()
string(FIND "${moduleinfo}" "\"Version\": \"${VERSION}\"" version_position)
if(version_position EQUAL -1)
    message(FATAL_ERROR "Package module metadata version does not match the project")
endif()
file(GLOB_RECURSE bundle_files "${staged_bundle}/*")
foreach(file IN LISTS bundle_files)
    if(NOT file STREQUAL staged_binary AND NOT file STREQUAL "${staged_bundle}/Contents/Resources/moduleinfo.json")
        message(FATAL_ERROR "Unexpected bundle file: ${file}")
    endif()
endforeach()

set(dependency_report "Windows x64 dependency audit (${COMPILER})\nCompiler runtimes linked statically. Imports must be Windows system DLLs.\n")
get_filename_component(tool_name "${DEPENDENCY_TOOL}" NAME)
foreach(binary IN ITEMS "${staged_binary}" "${staged_exe}")
    if(tool_name MATCHES "dumpbin")
        set(tool_option /DEPENDENTS)
    else()
        set(tool_option -p)
    endif()
    execute_process(COMMAND "${DEPENDENCY_TOOL}" ${tool_option} "${binary}"
        OUTPUT_VARIABLE imports ERROR_VARIABLE import_error RESULT_VARIABLE import_result)
    if(NOT import_result EQUAL 0)
        message(FATAL_ERROR "Dependency audit failed: ${import_error}")
    endif()
    string(TOLOWER "${imports}" imports)
    string(REGEX MATCHALL "[a-z0-9_.+-]+\\.dll" dlls "${imports}")
    list(REMOVE_DUPLICATES dlls)
    list(SORT dlls)
    if(NOT dlls)
        message(FATAL_ERROR "Dependency scanner returned no DLL imports")
    endif()
    set(system_dlls advapi32.dll bcrypt.dll comdlg32.dll crypt32.dll d2d1.dll d3d11.dll
        dcomp.dll dwmapi.dll dwrite.dll dxgi.dll gdi32.dll imm32.dll kernel32.dll
        msimg32.dll ntdll.dll ole32.dll oleaut32.dll rpcrt4.dll setupapi.dll shell32.dll
        shlwapi.dll user32.dll uxtheme.dll version.dll wininet.dll winmm.dll
        ws2_32.dll wsock32.dll ucrtbase.dll msvcrt.dll)
    get_filename_component(binary_name "${binary}" NAME)
    string(APPEND dependency_report "\n${binary_name}:\n")
    foreach(dll IN LISTS dlls)
        if(NOT dll IN_LIST system_dlls AND NOT dll MATCHES "^api-ms-win-.*\\.dll$")
            message(FATAL_ERROR "Unexpected non-system runtime dependency: ${dll}")
        endif()
        string(APPEND dependency_report "  ${dll}\n")
    endforeach()
endforeach()
file(WRITE "${stage}/DEPENDENCIES.txt" "${dependency_report}")
configure_file("${SOURCE_DIR}/Packaging/README.txt.in" "${stage}/README.txt" @ONLY)
file(COPY "${SOURCE_DIR}/README.md" "${SOURCE_DIR}/CHANGELOG.md" DESTINATION "${stage}")
if(NOT EXISTS "${REPO_DIR}/LICENSE")
    message(FATAL_ERROR "Release requires the owner-approved project LICENSE")
endif()
file(COPY "${REPO_DIR}/LICENSE" DESTINATION "${stage}")
set(license_status "MIT for own code; JUCE 7 / third-party terms separate")
file(COPY "${SOURCE_DIR}/Packaging/THIRD-PARTY-NOTICES.txt" DESTINATION "${stage}")
file(COPY_FILE "${JUCE_DIR}/LICENSE.md" "${stage}/JUCE-LICENSE.md")

execute_process(COMMAND "${GIT}" -C "${REPO_DIR}" rev-parse HEAD
    OUTPUT_VARIABLE commit OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND "${GIT}" -C "${REPO_DIR}" status --porcelain --untracked-files=normal
    OUTPUT_VARIABLE dirty OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
if(dirty STREQUAL "")
    set(source_status "clean")
else()
    set(source_status "dirty - commit alone does not identify these sources")
endif()
file(SHA256 "${staged_binary}" plugin_hash)
file(SHA256 "${staged_exe}" standalone_hash)
file(WRITE "${stage}/release-manifest.txt"
    "Product: TE-2350 Antigravity\nVersion: ${VERSION}\nCommit SHA: ${commit}\nSource status: ${source_status}\n"
    "Build type: ${CONFIG}\nPlatform: Windows\nArchitecture: x64\nCompiler: ${COMPILER}\n"
    "JUCE version: ${JUCE_VERSION}\nJUCE commit: ${JUCE_COMMIT}\n"
    "Preset format version: ${PRESET_FORMAT_VERSION}\nState version: ${STATE_VERSION}\n"
    "VST3 processor CID: ABCDEF019182FAEB5465416754323335\n"
    "VST3 controller CID: ABCDEF011234ABCD5465416754323335\n"
    "Qualification: full CTest inventory passed\nStandalone: developer preview; not a qualified audio-device product\n"
    "Licensing: ${license_status}\nVST3 SHA256: ${plugin_hash}\nStandalone SHA256: ${standalone_hash}\n"
    "ZIP SHA256: external SHA256SUMS.txt (avoids circular archive hash)\n")
file(GLOB_RECURSE payload RELATIVE "${stage}" "${stage}/*")
list(SORT payload)
set(checksums "")
foreach(file IN LISTS payload)
    file(SHA256 "${stage}/${file}" hash)
    string(APPEND checksums "${hash}  ${file}\n")
endforeach()
file(WRITE "${stage}/SHA256SUMS.txt" "${checksums}")
set(staging_archive "${BUILD_DIR}/release-staging/${package_name}.zip")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${staging_archive}" --format=zip -- "${package_name}"
    WORKING_DIRECTORY "${BUILD_DIR}/release-staging" COMMAND_ERROR_IS_FATAL ANY)
# Verify the extracted ZIP, with the original build paths and toolchain removed from PATH.
set(extract "${BUILD_DIR}/release-verify")
file(REMOVE_RECURSE "${extract}")
file(MAKE_DIRECTORY "${extract}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xf "${staging_archive}"
    WORKING_DIRECTORY "${extract}" COMMAND_ERROR_IS_FATAL ANY)
foreach(file IN LISTS payload)
    file(SHA256 "${stage}/${file}" before)
    file(SHA256 "${extract}/${package_name}/${file}" after)
    if(NOT before STREQUAL after)
        message(FATAL_ERROR "ZIP round-trip mismatch: ${file}")
    endif()
endforeach()
set(ENV{PATH} "$ENV{SystemRoot}/System32;$ENV{SystemRoot}")
execute_process(COMMAND "${SCANNER}" "${extract}/${package_name}/VST3/${bundle_name}"
    WORKING_DIRECTORY "${extract}" RESULT_VARIABLE scan_result)
if(NOT scan_result EQUAL 0)
    message(FATAL_ERROR "Final ZIP VST3 failed to load; no release artifact published")
endif()
file(MAKE_DIRECTORY "${output}")
file(COPY "${extract}/${package_name}" DESTINATION "${output}")
file(COPY_FILE "${staging_archive}" "${archive}")
file(SHA256 "${archive}" archive_hash)
file(WRITE "${output}/SHA256SUMS.txt" "${archive_hash}  ${package_name}.zip\n")
file(WRITE "${archive}.sha256" "${archive_hash}  ${package_name}.zip\n")
message(STATUS "Qualified ZIP: ${archive}")
